openapi: 3.0.1
info:
  title: monster-giant-elk
  x-cortex-tag: monster-giant-elk
  x-cortex-custom-metadata:
    alignment: neutral-good
    type: beast
    challenge_rating: 4
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
